// docs/lovable-source/src/components/page-header.tsx
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import type { ReactNode } from "react";

interface PageHeaderProps {
  eyebrow?: string;
  title: string;
  description?: string;
  actions?: ReactNode;
  className?: string;
}

export function PageHeader({ eyebrow, title, description, actions, className }: PageHeaderProps) {
  return (
    <motion.header
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className={cn(
        "flex flex-wrap items-end justify-between gap-4 border-b pb-5",
        className
      )}
    >
      <div className="space-y-1">
        {eyebrow && <p className="label-mono">{eyebrow}</p>}
        <h1 className="text-2xl font-semibold tracking-tight md:text-3xl">{title}</h1>
        {description && <p className="text-sm text-muted-foreground max-w-2xl">{description}</p>}
      </div>
      {actions && <div className="flex flex-wrap items-center gap-2">{actions}</div>}
    </motion.header>
  );
}

export function SectionHeader({
  title,
  description,
  actions,
}: {
  title: string;
  description?: string;
  actions?: ReactNode;
}) {
  return (
    <div className="flex flex-wrap items-end justify-between gap-3 mb-4">
      <div>
        <h2 className="text-base font-semibold tracking-tight">{title}</h2>
        {description && <p className="text-xs text-muted-foreground mt-0.5">{description}</p>}
      </div>
      {actions}
    </div>
  );
}

export function EmptyState({
  title,
  description,
  icon,
  action,
}: {
  title: string;
  description?: string;
  icon?: ReactNode;
  action?: ReactNode;
}) {
  return (
    <div className="relative overflow-hidden rounded-xl border bg-card p-10 text-center">
      <div className="absolute inset-0 blueprint-grid opacity-40 pointer-events-none" />
      <div className="relative mx-auto flex max-w-sm flex-col items-center gap-3">
        {icon && <div className="rounded-xl border bg-muted/40 p-3 text-primary">{icon}</div>}
        <h3 className="text-base font-semibold">{title}</h3>
        {description && <p className="text-sm text-muted-foreground">{description}</p>}
        {action && <div className="mt-2">{action}</div>}
      </div>
    </div>
  );
}

export function GlassCard({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <div className={cn("rounded-xl border glass shadow-elegant", className)}>
      {children}
    </div>
  );
}

// SLMS_UI/src/app/shared/components/page-header/page-header.component.ts
import { Component, input } from '@angular/core';
import { AppIconComponent } from "../app-icon/app-icon.component";
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-page-header',
  standalone: true,
  template: `
    <header class="mb-4 flex flex-wrap items-end justify-between gap-4 border-b border-[var(--border)] pb-4">
      <div class="space-y-1">
        @if (eyebrow()) {
          <p class="label-mono flex items-center gap-1.5">
            @if (isBack()) {
              <app-icon class='table-cursor' name="arrow-left" [size]="14" [routerLink]="routerLink()"></app-icon>
            }
            {{ eyebrow() }}
          </p>
        }
        <h1 class="text-2xl font-semibold tracking-tight md:text-3xl">{{ title() }}</h1>
        @if (description()) {
          <p class="max-w-2xl text-sm text-[var(--muted-foreground)]">{{ description() }}</p>
        }
      </div>
      <div class="flex flex-wrap items-center gap-2">
        <ng-content select="[actions]" />
      </div>
    </header>
  `,
  imports: [AppIconComponent, RouterLink],
})
export class PageHeaderComponent {
  readonly eyebrow = input<string>();
  readonly isBack = input<boolean>(false);
  readonly title = input.required<string>();
  readonly description = input<string>();
  readonly routerLink = input<string>();
}

@Component({
  selector: 'app-section-header',
  standalone: true,
  template: `
    <div class="mb-4 flex flex-wrap items-end justify-between gap-3">
      <div>
        <h2 class="text-base font-semibold tracking-tight">{{ title() }}</h2>
        @if (description()) {
          <p class="mt-0.5 text-xs text-[var(--muted-foreground)]">{{ description() }}</p>
        }
      </div>
      <ng-content select="[actions]" />
    </div>
  `,
})
export class SectionHeaderComponent {
  readonly title = input.required<string>();
  readonly description = input<string>();
}

@Component({
  selector: 'app-glass-card',
  standalone: true,
  template: `<div class="glass-card rounded-xl border glass shadow-elegant p-4"><ng-content /></div>`,
})
export class GlassCardComponent { }
