// SLMS_UI/src/app/features/auth/login/login.component.ts
import { Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Role } from '@core/models/auth.model';
import { AuthService } from '@core/services/auth.service';
import { ToastService } from '@core/services/toast.service';
import { LucideShield, LucideUser, LucideUsers } from '@lucide/angular';
import { ButtonComponent } from '@shared/components/button/button.component';
import { InputDirective } from '@shared/components/input/input.directive';
import { LabelDirective } from '@shared/components/label/label.directive';
import { AuthLayoutComponent } from 'src/app/layouts/auth-layout/auth-layout.component';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { LoginRequest } from '@core/models/AuthResponse.model';
import { OnboardingSteps } from '@core/enums/OnbardingSteps';
import { CommonService } from '@core/services/common.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    FormsModule,
    RouterLink,
    AuthLayoutComponent,
    InputDirective,
    LabelDirective,
  ],
  templateUrl: './login.component.html',
})
export class LoginComponent {
  private readonly auth = inject(AuthService);
  private readonly toast = inject(ToastService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private destroyRef = inject(DestroyRef);
  private readonly CommonService = inject(CommonService);

  readonly email = signal('');
  readonly password = signal('');
  readonly loader = signal(false);

  submit() {

    this.loader.set(true);

    const request: LoginRequest = {
      email: this.email(),
      password: this.password(),
    }
    this.auth.login(request).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (response) => {
        console.log('Login response:', response);
        if (response.success && response.data) {
          this.getRedirect(response.data.user.onboardingStep);
        } else {
          this.toast.error(response.message || 'Unable to sign in. Please try again.');
        }
        this.loader.set(false);
      },
      error: (error) => {
        this.toast.error(error.error.message || 'Unable to sign in. Please try again.');
        this.loader.set(false);
      }
    });
  }

  private getRedirect(onboardingStep: OnboardingSteps) {
    const config = this.CommonService.onboardingConfig[onboardingStep] ?? { route: '/dashboard', message: '' };
    this.toast.info(config.message ?? '');
    this.router.navigate([config.route]);
  }
}

<app-auth-layout eyebrow="Authentication" title="Sign in to your workspace"
    subtitle="Welcome back. Enter your organization email and password to manage library resources, members, circulation, and reports."
    [hasFooter]="true">
    <form #loginForm="ngForm" class="space-y-4" (ngSubmit)="submit()" novalidate>
        <div class="space-y-1.5">
            <label appLabel for="email">Email</label>
            <input appInput id="email" type="email" name="email" [(ngModel)]="email" #emailCtrl="ngModel"
                placeholder="admin@demo" required email />
            @if(emailCtrl.invalid && (emailCtrl.touched || loginForm.submitted)) {
            <div class="space-y-1 text-sm text-red-500">
                @if(emailCtrl.errors?.['required']) {
                <p>Email is required.</p>
                }
                @if(emailCtrl.errors?.['email']) {
                <p>Please enter a valid email address.</p>
                }

            </div>
            }
        </div>
        <div class="space-y-1.5">
            <div class="flex items-center justify-between">
                <label appLabel for="password">Password</label>
                <a routerLink="/forgot-password" class="text-xs text-primary hover:underline">Forgot?</a>
            </div>
            <input appInput id="password" type="password" name="password" [(ngModel)]="password" #passwordCtrl="ngModel"
                placeholder="demo123" required />
            @if(passwordCtrl.invalid && (passwordCtrl.touched || loginForm.submitted)) {
            <div class="space-y-1 text-sm text-red-500">
                @if(passwordCtrl.errors?.['required']) {
                <p>Password is required.</p>
                }
            </div>
            }
        </div>
         <button type="submit" class="ui-btn-primary w-full cursorPointer"
            [disabled]="loader() || (loginForm.invalid ?? true)">
             {{ loader() ? 'Signing in…' : 'Sign in' }}
        </button>
        <button type="button" (click)="submit()" class="ui-btn-outline w-full cursorPointer" >Sign in with one-time
            code</button>
        <div class="relative py-1">
            <div class="absolute inset-0 flex items-center"><span class="w-full border-t"></span></div>
            <div class="relative flex justify-center"><span class="bg-background px-2 mono-label">or</span></div>
        </div>
    </form>

    <div footer>
        <p class="text-center mb-2 text-[11px] text-muted-foreground">Sign up a temp account with an institution, branch
            &amp; library.</p>
        <p class="text-center text-sm text-[var(--muted-foreground)]">New here? <a routerLink="/register"
                class="text-[var(--primary)] hover:underline">Create operator account</a></p>
    </div>
</app-auth-layout>

// docs/lovable-source/src/routes/login.tsx
import { createFileRoute, Link } from "@tanstack/react-router";
import { AuthShell } from "@/components/auth-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuth, type Role } from "@/lib/store/auth";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Shield, Users, User } from "lucide-react";

export const Route = createFileRoute("/login")({
  head: () => ({ meta: [{ title: "Sign in — SmartLibrary" }] }),
  component: LoginPage,
});

const QUICK: { role: Role; email: string; label: string; icon: typeof Shield; hint: string }[] = [
  { role: "admin", email: "admin@demo", label: "Admin", icon: Shield, hint: "Full access · admin area" },
  { role: "staff", email: "staff@demo", label: "Staff", icon: Users, hint: "Members, seats, attendance" },
  { role: "member", email: "member@demo", label: "Member", icon: User, hint: "Read-only access" },
];

function LoginPage() {
  const { login, loginAs, isAuthenticated, initialized } = useAuth();
  
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);

  const getRedirect = (): string => {
    if (typeof window === "undefined") return "/dashboard";
    const p = new URLSearchParams(window.location.search).get("redirect");
    if (p && p.startsWith("/") && !p.startsWith("//")) return p;
    return "/dashboard";
  };

  useEffect(() => {
    if (initialized && isAuthenticated && typeof window !== "undefined") {
      window.location.replace(getRedirect());
    }
  }, [initialized, isAuthenticated]);

  const goAfterAuth = () => {
    if (typeof window !== "undefined") window.location.replace(getRedirect());
  };

  const quickLogin = async (role: Role) => {
    setBusy(true);
    try {
      await loginAs(role);
      toast.success(`Signed in as ${role}`);
      goAfterAuth();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Sign-in failed");
    } finally {
      setBusy(false);
    }
  };


  return (
    <AuthShell
      title="Sign in to your workspace"
      subtitle="Mock auth — pick a role or use seeded credentials below."
      footer={<>New here? <Link to="/register" className="text-primary hover:underline">Create an account</Link></>}
    >
      <div className="space-y-2">
        {QUICK.map(({ role, label, icon: Icon, hint }) => (
          <button
            key={role}
            type="button"
            disabled={busy}
            onClick={() => quickLogin(role)}
            className="w-full flex items-center gap-3 rounded-lg border bg-card p-3 text-left transition hover:bg-muted/40 disabled:opacity-50"
          >
            <span className="flex h-9 w-9 items-center justify-center rounded-md bg-primary/10 text-primary">
              <Icon className="h-4 w-4" />
            </span>
            <span className="flex-1">
              <span className="block text-sm font-medium">Continue as {label}</span>
              <span className="block text-xs text-muted-foreground">{hint}</span>
            </span>
            <span className="label-mono">demo123</span>
          </button>
        ))}
      </div>

      <div className="flex items-center gap-3 my-5">
        <div className="flex-1 h-px bg-border" />
        <span className="label-mono">or with email</span>
        <div className="flex-1 h-px bg-border" />
      </div>

      <form
        className="space-y-4"
        onSubmit={async (e) => {
          e.preventDefault();
          setBusy(true);
          try {
            await login(email, password);
            toast.success("Welcome back.");
            goAfterAuth();
          } catch (err) {
            toast.error(err instanceof Error ? err.message : "Sign-in failed");
          } finally {
            setBusy(false);
          }
        }}
      >

        <div className="space-y-1.5">
          <Label htmlFor="email">Email</Label>
          <Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="admin@demo" required />
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <Label htmlFor="password">Password</Label>
            <Link to="/forgot-password" className="text-xs text-primary hover:underline">Forgot?</Link>
          </div>
          <Input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="demo123" required />
        </div>
        <Button type="submit" className="w-full" disabled={busy}>
          {busy ? "Signing in…" : "Sign in"}
        </Button>
      </form>
    </AuthShell>
  );
}
