// docs/lovable-source/src/components/renew-plan-dialog.tsx
import { useMemo } from "react";
import { ArrowRight, CalendarCheck, RotateCcw } from "lucide-react";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
  AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { previewRenewal } from "@/lib/mock/members-demo";
import { cn } from "@/lib/utils";

export type RenewTarget = {
  id: string;
  name: string;
  membership: string;
  expiry: string;
  daysLeft: number;
  feesOwed?: number;
};

const fmt = (iso: string) =>
  new Date(`${iso}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" });

export function RenewPlanDialog({
  target,
  onOpenChange,
  onConfirm,
}: {
  target: RenewTarget | null;
  onOpenChange: (open: boolean) => void;
  onConfirm: (t: RenewTarget) => void;
}) {
  const preview = useMemo(() => previewRenewal(target?.membership ?? "Basic"), [target?.membership]);

  return (
    <AlertDialog open={!!target} onOpenChange={onOpenChange}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle className="flex items-center gap-2">
            <RotateCcw className="h-4 w-4" /> Renew membership
          </AlertDialogTitle>
          <AlertDialogDescription>
            {target
              ? `Extend ${target.name}'s ${target.membership} plan by ${preview.months === 12 ? "12 months" : "1 month"} from today.`
              : ""}
          </AlertDialogDescription>
        </AlertDialogHeader>

        {target && (
          <div className="rounded-lg border bg-muted/30 p-3">
            <div className="flex items-center gap-3">
              <div className="flex-1">
                <div className="text-[10px] uppercase tracking-wide text-muted-foreground">Current expiry</div>
                <div className={cn("text-sm font-medium tabular-nums", target.daysLeft < 0 && "text-destructive")}>
                  {fmt(target.expiry)}
                </div>
                <div className="text-[11px] text-muted-foreground">
                  {target.daysLeft < 0 ? `${Math.abs(target.daysLeft)} days ago` : `in ${target.daysLeft} days`}
                </div>
              </div>
              <ArrowRight className="h-4 w-4 text-muted-foreground shrink-0" />
              <div className="flex-1">
                <div className="text-[10px] uppercase tracking-wide text-muted-foreground">New expiry</div>
                <div className="text-sm font-medium tabular-nums text-success flex items-center gap-1">
                  <CalendarCheck className="h-3.5 w-3.5" /> {fmt(preview.date)}
                </div>
                <div className="text-[11px] text-muted-foreground">
                  {preview.months === 12 ? "+12 months" : "+1 month"}
                </div>
              </div>
            </div>
            {(target.feesOwed ?? 0) > 0 && (
              <div className="mt-3 text-xs text-destructive">
                Outstanding dues of ₹{(target.feesOwed ?? 0).toLocaleString()} remain after renewal.
              </div>
            )}
          </div>
        )}

        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction onClick={() => target && onConfirm(target)}>Confirm renewal</AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}

// SLMS_UI/src/app/features/members/components/renew-plan-dialog/renew-plan-dialog.component.ts
import { Component, computed, input, output } from '@angular/core';
import { CurrencyPipe } from '@angular/common';
import { LucideArrowRight, LucideCalendarCheck, LucideRotateCcw, LucideX } from '@lucide/angular';
import { ButtonComponent } from '@shared/components/button/button.component';
import { formatRenewDate, previewRenewal, RenewTarget } from '../../member-lifecycle.util';

@Component({
  selector: 'app-renew-plan-dialog',
  imports: [ButtonComponent, CurrencyPipe, LucideArrowRight, LucideCalendarCheck, LucideRotateCcw, LucideX],
  templateUrl: './renew-plan-dialog.component.html',
})
export class RenewPlanDialogComponent {
  readonly target = input<RenewTarget | null>(null);
  readonly busy = input(false);

  readonly confirm = output<RenewTarget>();
  readonly closed = output<void>();

  readonly preview = computed(() => previewRenewal(this.target()?.planDurationInDays ?? 30));
  readonly formatRenewDate = formatRenewDate;
  readonly Math = Math;

  onClose(): void {
    this.closed.emit();
  }

  onConfirm(): void {
    const t = this.target();
    if (t) this.confirm.emit(t);
  }
}

@if (target(); as t) {
<div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 p-4" (click)="onClose()">
  <div class="w-full max-w-md rounded-xl border bg-background shadow-xl" (click)="$event.stopPropagation()">
    <div class="flex items-center justify-between border-b px-5 py-4">
      <h2 class="text-lg font-semibold flex items-center gap-2">
        <svg lucideRotateCcw class="h-4 w-4"></svg> Renew membership
      </h2>
      <button type="button" class="inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-accent" (click)="onClose()">
        <svg lucideX class="h-4 w-4"></svg>
      </button>
    </div>

    <div class="px-5 py-4 space-y-4">
      <p class="text-sm text-muted-foreground">
        Extend {{ t.name }}'s {{ t.plan }} plan by {{ preview().label }} from today.
      </p>

      <div class="rounded-lg border bg-muted/30 p-3">
        <div class="flex items-center gap-3">
          <div class="flex-1">
            <div class="text-[10px] uppercase tracking-wide text-muted-foreground">Current expiry</div>
            <div class="text-sm font-medium tabular-nums" [class]="t.daysLeft < 0 ? 'text-destructive' : ''">
              {{ formatRenewDate(t.expiry) }}
            </div>
            <div class="text-[11px] text-muted-foreground">
              @if (t.daysLeft < 0) {
                {{ Math.abs(t.daysLeft) }} days ago
              } @else if (t.daysLeft === 0) {
                today
              } @else {
                in {{ t.daysLeft }} days
              }
            </div>
          </div>
          <svg lucideArrowRight class="h-4 w-4 text-muted-foreground shrink-0"></svg>
          <div class="flex-1">
            <div class="text-[10px] uppercase tracking-wide text-muted-foreground">New expiry</div>
            <div class="text-sm font-medium tabular-nums text-success flex items-center gap-1">
              <svg lucideCalendarCheck class="h-3.5 w-3.5"></svg>
              {{ formatRenewDate(preview().date) }}
            </div>
            <div class="text-[11px] text-muted-foreground">{{ preview().label }}</div>
          </div>
        </div>
        @if (t.feesOwed > 0) {
        <div class="mt-3 text-xs text-destructive">
          Outstanding dues of {{ t.feesOwed | currency:'INR' }} remain after renewal.
        </div>
        }
      </div>
    </div>

    <div class="flex justify-end gap-2 border-t px-5 py-4">
      <app-button variant="outline" size="sm" [disabled]="busy()" (click)="onClose()">Cancel</app-button>
      <app-button size="sm" [disabled]="busy()" (click)="onConfirm()">
        {{ busy() ? 'Renewing…' : 'Confirm renewal' }}
      </app-button>
    </div>
  </div>
</div>
}
