// docs/lovable-source/src/components/topbar.tsx
import { SidebarTrigger } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Bell, Moon, Sun, Search, LogOut } from "lucide-react";
import { useTheme } from "@/lib/store/theme";
import { useAuth } from "@/lib/store/auth";
import { useRouterState, Link, useNavigate } from "@tanstack/react-router";
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem,
  DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { notifications } from "@/lib/mock/data";
import {
  Popover, PopoverContent, PopoverTrigger,
} from "@/components/ui/popover";

export function Topbar() {
  const { mode, toggle } = useTheme();
  const { user, logout } = useAuth();
  const navigate = useNavigate() as (opts: any) => void;
  const pathname = useRouterState({ select: (s) => s.location.pathname });
  const segs = pathname.split("/").filter(Boolean);
  const unread = notifications.filter((n) => !n.read).length;

  return (
    <header className="sticky top-0 z-30 flex h-14 items-center gap-3 border-b bg-background/80 backdrop-blur px-3 md:px-4">
      <SidebarTrigger />
      <nav className="hidden md:flex items-center gap-1.5 text-sm">
        {segs.map((seg, i) => {
          const href = "/" + segs.slice(0, i + 1).join("/");
          const isLast = i === segs.length - 1;
          return (
            <span key={href} className="flex items-center gap-1.5">
              {i > 0 && <span className="text-muted-foreground/50">/</span>}
              {isLast ? (
                <span className="font-medium capitalize">{seg.replace(/-/g, " ")}</span>
              ) : (
                <Link to={href as any} className="text-muted-foreground hover:text-foreground capitalize">
                  {seg.replace(/-/g, " ")}
                </Link>
              )}
            </span>
          );
        })}
      </nav>
      <div className="ml-auto flex items-center gap-2">
        <div className="relative hidden md:block">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search members, seats, branches…"
            className="pl-8 h-9 w-72 bg-muted/40"
          />
          <kbd className="absolute right-2 top-1/2 -translate-y-1/2 hidden md:inline-flex h-5 items-center rounded border bg-background px-1.5 font-mono text-[10px] text-muted-foreground">
            ⌘K
          </kbd>
        </div>

        <Popover>
          <PopoverTrigger asChild>
            <Button variant="ghost" size="icon" className="relative">
              <Bell className="h-4 w-4" />
              {unread > 0 && (
                <span className="absolute top-1.5 right-1.5 h-2 w-2 rounded-full bg-destructive ring-2 ring-background" />
              )}
            </Button>
          </PopoverTrigger>
          <PopoverContent align="end" className="w-80 p-0">
            <div className="flex items-center justify-between border-b px-3 py-2">
              <div className="text-sm font-semibold">Notifications</div>
              <Link to="/notifications" className="text-xs text-primary hover:underline">View all</Link>
            </div>
            <div className="max-h-80 overflow-y-auto divide-y">
              {notifications.slice(0, 5).map((n) => (
                <div key={n.id} className="p-3 hover:bg-muted/50">
                  <div className="flex items-center justify-between">
                    <div className="text-sm font-medium">{n.title}</div>
                    <span className="label-mono">{n.timestamp}</span>
                  </div>
                  <p className="text-xs text-muted-foreground mt-0.5">{n.message}</p>
                </div>
              ))}
            </div>
          </PopoverContent>
        </Popover>

        <Button variant="ghost" size="icon" onClick={toggle} aria-label="Toggle theme">
          {mode === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
        </Button>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <button className="flex items-center gap-2 rounded-md border px-1 py-1 hover:bg-muted/50">
              <Avatar className="h-7 w-7">
                <AvatarImage src={user?.avatar} />
                <AvatarFallback className="text-xs">
                  {user?.name?.split(" ").map((p) => p[0]).slice(0, 2).join("")}
                </AvatarFallback>
              </Avatar>
              <div className="hidden md:block pr-2 text-left">
                <div className="text-xs font-semibold leading-tight">{user?.name}</div>
                <div className="label-mono leading-tight">{user?.role}</div>
              </div>
            </button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-56">
            <DropdownMenuLabel>
              <div className="text-sm">{user?.name}</div>
              <div className="text-xs text-muted-foreground">{user?.email}</div>
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => navigate({ to: "/settings/profile" })}>
              Profile
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => navigate({ to: "/settings" })}>
              Settings
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              onClick={async () => {
                await logout();
                navigate({ to: "/login" });
              }}
            >
              <LogOut className="mr-2 h-4 w-4" /> Sign out
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  );
}

// SLMS_UI/src/app/layouts/topbar/topbar.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { filter, map, startWith } from 'rxjs';
import { LucideBell, LucideLogOut, LucideMoon, LucideSearch, LucideSun } from '@lucide/angular';
import { AuthService } from '../../core/services/auth.service';
import { ThemeService } from '../../core/services/theme.service';
import { SidebarService } from '../sidebar/sidebar.service';
import { InputDirective } from '@shared/components/input/input.directive';
import { StorageService } from '@core/services/storage.service';

/** Sticky header with breadcrumbs, search, notifications, theme toggle and account menu. */
@Component({
  selector: 'app-topbar',
  standalone: true,
  imports: [RouterLink, InputDirective, LucideBell, LucideMoon, LucideSun, LucideSearch, LucideLogOut],
  template: `
    <header class="fixed inset-x-0 top-0 z-30 flex h-14 items-center gap-3 border-b bg-background/80 backdrop-blur px-3 md:px-4">
      <button type="button" (click)="sidebar.toggle()" class="rounded-md border p-1.5 hover:bg-muted/50" aria-label="Toggle sidebar">
        <span class="block h-4 w-4">☰</span>
      </button>

      <!-- <nav class="hidden md:flex items-center gap-1.5 text-sm">
        @for (seg of segments(); track seg.href; let last = $last) {
          <span class="flex items-center gap-1.5">
            @if (!$first) { <span class="text-muted-foreground/50">/</span> }
            @if (last) {
              <span class="font-medium capitalize">{{ seg.label }}</span>
            } @else {
              <a [routerLink]="seg.href" class="text-muted-foreground hover:text-foreground capitalize">{{ seg.label }}</a>
            }
          </span>
        }
      </nav> -->

      <div class="ml-auto flex items-center gap-2">
        <div class="relative hidden md:block">
          <svg lucideSearch class="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground"></svg>
          <input appInput placeholder="Search members, seats, branches…" class="pl-8 h-9 w-72 bg-muted/40" />
        </div>

        <!-- <div class="relative">
          <button type="button" (click)="notifOpen.set(!notifOpen())" class="relative rounded-md p-2 hover:bg-accent" aria-label="Notifications">
            <svg lucideBell class="h-4 w-4"></svg>
            @if (unread() > 0) {
              <span class="absolute top-1.5 right-1.5 h-2 w-2 rounded-full bg-destructive ring-2 ring-background"></span>
            }
          </button>
          @if (notifOpen()) {
            <div class="fixed inset-0 z-40" (click)="notifOpen.set(false)"></div>
            <div class="absolute right-0 z-50 mt-2 w-80 rounded-md border bg-popover shadow-elegant">
              <div class="flex items-center justify-between border-b px-3 py-2">
                <div class="text-sm font-semibold">Notifications</div>
                <a routerLink="/notifications" class="text-xs text-primary hover:underline" (click)="notifOpen.set(false)">View all</a>
              </div>
              <div class="max-h-80 overflow-y-auto divide-y">
                @for (n of notifications; track n.id) {
                  <div class="p-3 hover:bg-muted/50">
                    <div class="flex items-center justify-between">
                      <div class="text-sm font-medium">{{ n.title }}</div>
                      <span class="label-mono">{{ n.timestamp }}</span>
                    </div>
                    <p class="text-xs text-muted-foreground mt-0.5">{{ n.message }}</p>
                  </div>
                }
              </div>
            </div>
          }
        </div> -->

        <button type="button" (click)="theme.toggle()" class="rounded-md p-2 hover:bg-accent" aria-label="Toggle theme">
          @if (theme.mode() === 'dark') {
            <svg lucideSun class="h-4 w-4"></svg>
          } @else {
            <svg lucideMoon class="h-4 w-4"></svg>
          }
        </button>

        <div class="relative">
          <button type="button" (click)="userOpen.set(!userOpen())" class="flex items-center gap-2 rounded-md border px-1 py-1 hover:bg-muted/50">
            <span class="grid h-7 w-7 place-items-center rounded-full bg-muted text-xs font-semibold">{{ initials() }}</span>
            <span class="hidden md:block pr-2 text-left">
              <span class="block text-xs font-semibold leading-tight">{{storageService.user()?.fullName ?? storageService.user()?.userName }}</span>
              <span class="label-mono leading-tight">{{ storageService.user()?.roles }}</span>
            </span>
          </button>
          @if (userOpen()) {
            <div class="fixed inset-0 z-40" (click)="userOpen.set(false)"></div>
            <div class="absolute right-0 z-50 mt-2 w-56 rounded-md border bg-popover p-1 shadow-elegant">
              <div class="px-2 py-1.5">
                <div class="text-sm">{{storageService.user()?.fullName ?? storageService.user()?.userName }}</div>
                <div class="text-xs text-muted-foreground">{{ storageService.user()?.email }}</div>
              </div>
              <div class="my-1 h-px bg-border"></div>
              <a routerLink="/settings/profile" class="block rounded-sm px-2 py-1.5 text-sm hover:bg-muted" (click)="userOpen.set(false)">Profile</a>
              <a routerLink="/settings" class="block rounded-sm px-2 py-1.5 text-sm hover:bg-muted" (click)="userOpen.set(false)">Settings</a>
              <div class="my-1 h-px bg-border"></div>
              <button type="button" (click)="signOut()" class="flex w-full items-center rounded-sm px-2 py-1.5 text-left text-sm hover:bg-muted">
                <svg lucideLogOut class="mr-2 h-4 w-4"></svg> Sign out
              </button>
            </div>
          }
        </div>
      </div>
    </header>
  `,
})
export class TopbarComponent {
  protected readonly sidebar = inject(SidebarService);
  protected readonly theme = inject(ThemeService);
  protected readonly auth = inject(AuthService);
  protected readonly storageService = inject(StorageService);
  private readonly router = inject(Router);

  readonly notifOpen = signal(false);
  readonly userOpen = signal(false);

  readonly initials = computed(() => {
    const name = this.storageService.user()?.fullName ?? this.storageService.user()?.userName ?? this.storageService.user()?.email;
    return name?.split(' ').map((p) => p[0]).slice(0, 2).join('').toUpperCase();
  });

  private readonly url = toSignal(
    this.router.events.pipe(
      filter((e) => e instanceof NavigationEnd),
      map(() => this.router.url),
      startWith(this.router.url),
    ),
    { initialValue: this.router.url },
  );

  readonly segments = computed(() => {
    const path = this.url().split('?')[0];
    const parts = path.split('/').filter(Boolean);
    return parts.map((seg, i) => ({
      href: '/' + parts.slice(0, i + 1).join('/'),
      label: seg.replace(/-/g, ' '),
    }));
  });

  async signOut(): Promise<void> {
    this.userOpen.set(false);
    await this.auth.logout();
    await this.router.navigateByUrl('/login');
  }
}
